2. Generate at random 3 matrices of size 3 x 3 and fill each entry with a random integer chosen from -10 to 10. Use an existing
package to compute the inverse of each matrix if it exists. Include in your report:

- Each of the 3 matrices
- The inverses computed with the package
- Compute the product of each matrix with its inverse to check that you obtain the identity matrix.

In [1]:
import numpy as np

In [2]:
# generate 3 matrices of size 3x3 and fill with random integers from -10 to 10
matrices = []
for i in range(3):
    matrices.append(np.random.randint(-10, 10, (3, 3)))
matrices

[array([[-7, -2, -1],
        [-3, -3,  1],
        [-3, -1, -2]]),
 array([[ 1, -8, -2],
        [-4, -8, -4],
        [ 6, -6, -9]]),
 array([[ 1,  2, -3],
        [ 5,  6, -2],
        [-9,  0,  3]])]

In [3]:
# find the inverse of each matrix using the numpy linalg package
inv_matrices = []
for i in matrices:
    inv_matrices.append(np.linalg.inv(i))
inv_matrices

[array([[-0.28,  0.12,  0.2 ],
        [ 0.36, -0.44, -0.4 ],
        [ 0.24,  0.04, -0.6 ]]),
 array([[ 0.125     , -0.15625   ,  0.04166667],
        [-0.15625   ,  0.0078125 ,  0.03125   ],
        [ 0.1875    , -0.109375  , -0.10416667]]),
 array([[-0.13043478,  0.04347826, -0.10144928],
        [-0.02173913,  0.17391304,  0.0942029 ],
        [-0.39130435,  0.13043478,  0.02898551]])]

In [4]:
# compute the product of the inverse matrix and original matrix to double check that 
# the identity matrix is obtained
identity_matrices = []
for i in range(len(inv_matrices)):
    identity_matrices.append(matrices[i] @ inv_matrices[i])
identity_matrices

[array([[ 1.00000000e+00,  2.08166817e-17,  0.00000000e+00],
        [-1.38777878e-16,  1.00000000e+00, -1.11022302e-16],
        [-5.55111512e-17, -1.38777878e-17,  1.00000000e+00]]),
 array([[ 1.00000000e+00, -1.11022302e-16, -1.94289029e-16],
        [-1.11022302e-16,  1.00000000e+00, -1.11022302e-16],
        [-5.55111512e-17,  1.38777878e-17,  1.00000000e+00]]),
 array([[ 1.00000000e+00, -2.77555756e-17,  0.00000000e+00],
        [ 1.11022302e-16,  1.00000000e+00,  8.32667268e-17],
        [-1.66533454e-16,  8.32667268e-17,  1.00000000e+00]])]