2. Generate at random 3 matrices of size 3 x 3 and fill each entry with a random integer chosen from -10 to 10. Use an existing
package to compute the inverse of each matrix if it exists. Include in your report:

- Each of the 3 matrices
- The inverses computed with the package
- Compute the product of each matrix with its inverse to check that you obtain the identity matrix.

In [3]:
import numpy as np

In [24]:
matrix1 = np.random.randint(-10 , 10, (3, 3), dtype="l")
matrix1

array([[-10,  -2,  -2],
       [  4,  -5,  -8],
       [ -8,   6,  -7]])

In [35]:
matrix2 = np.random.randint(-10 , 10, (3, 3), dtype="l")
matrix2

array([[-6, -9, -7],
       [ 2, -5,  8],
       [ 4, -7, -6]])

In [37]:
matrix3 = np.random.randint(-10 , 10, (3, 3), dtype="l")
matrix3

array([[ 6, -8,  8],
       [-4, -3, -1],
       [-1, -2, -9]])

In [25]:
# inverse of matrix1 using numpy's linalg package
inv1 = np.linalg.inv(matrix1)
inv1

array([[-0.08452138,  0.02647658, -0.00610998],
       [-0.09368635, -0.05498982,  0.08961303],
       [ 0.01629328, -0.07739308, -0.05906314]])

In [39]:
inv2 = np.linalg.inv(matrix2)
inv2

array([[-0.09014675,  0.00524109,  0.11215933],
       [-0.04612159, -0.06708595, -0.03563941],
       [-0.00628931,  0.08176101, -0.05031447]])

In [40]:
inv3 = np.linalg.inv(matrix3)
inv3

array([[ 0.05319149, -0.18723404,  0.06808511],
       [-0.07446809, -0.09787234, -0.05531915],
       [ 0.0106383 ,  0.04255319, -0.10638298]])

In [31]:
# compute the product of the inverse1 with matrix1 to check that identity matrix is obtained
inv1 @ matrix1

array([[ 1.00000000e+00,  2.08166817e-17, -3.81639165e-17],
       [ 1.11022302e-16,  1.00000000e+00,  2.22044605e-16],
       [ 0.00000000e+00,  1.38777878e-17,  1.00000000e+00]])

In [41]:
inv2 @ matrix2

array([[ 1.00000000e+00,  0.00000000e+00,  2.22044605e-16],
       [-8.32667268e-17,  1.00000000e+00, -1.94289029e-16],
       [ 0.00000000e+00,  3.46944695e-17,  1.00000000e+00]])

In [42]:
inv3 @ matrix3

array([[ 1.00000000e+00,  3.33066907e-16,  0.00000000e+00],
       [-1.38777878e-17,  1.00000000e+00,  4.16333634e-17],
       [-1.38777878e-17, -2.77555756e-17,  1.00000000e+00]])