2. Generate at random 3 matrices of size 3 x 3 and fill each entry with a random integer chosen from -10 to 10. Use an existing
package to compute the inverse of each matrix if it exists. Include in your report:

- Each of the 3 matrices
- The inverses computed with the package
- Compute the product of each matrix with its inverse to check that you obtain the identity matrix.

In [44]:
import numpy as np

In [46]:
# generate 3 matrices of size 3x3 and fill with random integers from -10 to 10
matrices = []
for i in range(3):
    matrices.append(np.random.randint(-10, 10, (3, 3), dtype="l"))
matrices

[array([[-10,  -1,   2],
        [ -4,  -4,  -3],
        [ -1,   3,   4]]),
 array([[ 4,  3, -1],
        [-8,  0, -2],
        [ 1, -2, -5]]),
 array([[ 8, -2, -5],
        [ 6, -9, -3],
        [ 8,  3,  8]])]

In [48]:
# find the inverse of each matrix using the numpy linalg package
inv_matrices = []
for i in matrices:
    inv_matrices.append(np.linalg.inv(i))
inv_matrices

[array([[-0.36842105,  0.52631579,  0.57894737],
        [ 1.        , -2.        , -2.        ],
        [-0.84210526,  1.63157895,  1.89473684]]),
 array([[ 0.02531646, -0.10759494,  0.03797468],
        [ 0.26582278,  0.12025316, -0.10126582],
        [-0.10126582, -0.06962025, -0.15189873]]),
 array([[ 0.07777778, -0.00123457,  0.04814815],
        [ 0.08888889, -0.12839506,  0.00740741],
        [-0.11111111,  0.04938272,  0.07407407]])]

In [52]:
# compute the product of the inverse matrix and original matrix to double check that 
# the identity matrix is obtained
identity_matrices = []
for i in range(len(inv_matrices)):
    identity_matrices.append(matrices[i] @ inv_matrices[i])
identity_matrices

[array([[ 1.00000000e+00, -8.88178420e-16,  0.00000000e+00],
        [-2.22044605e-16,  1.00000000e+00,  6.66133815e-16],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]),
 array([[ 1.00000000e+00, -1.38777878e-17,  2.77555756e-17],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [ 6.93889390e-17, -4.16333634e-17,  1.00000000e+00]]),
 array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00, -1.11022302e-16,  1.00000000e+00]])]